export type TProvince =
  | "beijing"
  | "shanghai"
  | "tianjin"
  | "chongqing"
  | "hebei"
  | "shanxi"
  | "neimeng"
  | "liaoning"
  | "jilin"
  | "heilongjiang"
  | "jiangsu"
  | "zhejiang"
  | "anhui"
  | "fujian"
  | "jiangxi"
  | "shandong"
  | "henan"
  | "hubei"
  | "hunan"
  | "guangdong"
  | "guangxi"
  | "hainan"
  | "sichuan"
  | "guizhou"
  | "yunnan"
  | "xizang"
  | "shaanxi"
  | "gansu"
  | "qinghai"
  | "ningxia"
  | "xinjiang"
  | "outside"
  | ""
export type TISP = "chinatelecom" | "cmcc" | "chinaunicom" | "cbn" | "other" | ""

export interface IConfig {
  province: TProvince
  isp: TISP
}
